server.port=8080
spring.application.name=clima-service
spring.threads.virtual.enabled=true
weather.api.key=9dff4b38b7ba4c1bb93223449260507
weather.api.url=https://api.weatherapi.com/v1
weather.location=Buenos Aires

humedad=60
temperatura=35.0

twilio.api.key=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
email.remitente=jbriselli@frba.utn.edu.ar